[forcebindip]
# Use either iface or ip. iface is safer when the virtual adapter IP changes.
iface={0983F27C-91A5-4742-A6C8-C5AFF893F495}
# ip=10.27.238.154

# For old 32-bit Warcraft III, run the build-x86 launcher.
exe=G:\War3_1.27a\Warcraft3-11hf\war3.exe
cwd=G:\War3_1.27a\Warcraft3-11hf
args=-window

# Usually not needed. By default the launcher loads bindip_hook.dll next to itself.
# dll=C:\Path\bindip_hook.dll
